import React from 'react';
import { EventChart } from './components/event-chart';

const eventData = [
    { event: 'REJECT BID', properties: { time: 1725843651, distinct_id: 'sahno@icloud.com', $insert_id: 'CguowDnaAqFDcgewdApljxEmwlbdAzigtkzi', $lib_version: '0.18.0', $mp_api_endpoint: 'api.mixpanel.com', $mp_api_timestamp_ms: 1725843651432, $user_id: 'sahno@icloud.com', error: 'Rating 0', freelancer: 'Tamila Rozkova', mp_lib: 'node', mp_processing_time_ms: 1725843652414, name_event: 'REJECT BID', scanName: '🇺🇸 Tamila Rozhkova', team: 'BandIT', test: true } },
    { event: 'REJECT BID', properties: { time: 1725847248, distinct_id: 'sahno@icloud.com', $insert_id: 'kAvttuvotlaglfcCpmDqwebsfrfAovbvtCdr', $lib_version: '0.18.0', $mp_api_endpoint: 'api.mixpanel.com', $mp_api_timestamp_ms: 1725847248383, $user_id: 'sahno@icloud.com', error: 'Rating 0', freelancer: 'Tamila Rozkova', mp_lib: 'node', mp_processing_time_ms: 1725847248769, name_event: 'REJECT BID', scanName: '🇺🇸 Tamila Rozhkova', team: 'BandIT', test: true } },
    { event: 'SEND BID', properties: { time: 1725847283, distinct_id: 'sahno@icloud.com', $insert_id: 'lvCuslfweCrvfgkrFatdljkiziADDoaAokDA', $lib_version: '0.18.0', $mp_api_endpoint: 'api.mixpanel.com', $mp_api_timestamp_ms: 1725847283890, $user_id: 'sahno@icloud.com', coverLetter: 'Hey there!\n' + '\n' + "Hope you're doing great 😊. My name's Tamila Rozkova and I'm really excited about the chance to work on your WordPress Development and SEO project. I have a good amount of experience with WordPress and SEO, so I think I'm the right fit for w", employerAvgHourRatePaid: '31.73$/hour', employerHireRate: '88%', employerTotalRating: 5, employerTotalSpent: '$50K+', freelancer: 'Tamila Rozkova', mp_lib: 'node', mp_processing_time_ms: 1725847284857, name_event: 'SEND BID', publishedDate: 'Posted 20 minutes ago', questionAnswerPairs: null, requiredConnects: '19 Connects', scanName: '🇺🇸 Tamila Rozhkova', targetLink: 'https://www.upwork.com/jobs/~021832957216986184476', team: 'BandIT', test: true } },
    { event: 'SEND BID', properties: { time: 1725850885, distinct_id: 'sahno@icloud.com', $insert_id: 'EsvzgfsrEEgxbAncxEwiFidAjCCytggyboxE', $lib_version: '0.18.0', $mp_api_endpoint: 'api.mixpanel.com', $mp_api_timestamp_ms: 1725850885576, $user_id: 'sahno@icloud.com', coverLetter: 'Hey there! 😊\n' + '\n' + "I'm Tamila Rozkova, and I'd love to help you redesign your website. I think I’m a great fit for this project because I have solid experience with web design projects and I'm pretty good at HTML, CSS, and JavaScript. 🎨🌐\n" + '\n' + 'I’ve wor', employerAvgHourRatePaid: '54.99$/hour', employerHireRate: '41%', employerTotalRating: 5, employerTotalSpent: '$40K+', freelancer: 'Tamila Rozkova', mp_lib: 'node', mp_processing_time_ms: 1725850886638, name_event: 'SEND BID', publishedDate: 'Posted 48 minutes ago', questionAnswerPairs: null, requiredConnects: '18 Connects', scanName: '🇺🇸 Tamila Rozhkova', targetLink: 'https://www.upwork.com/jobs/~021832965106539117340', team: 'BandIT', test: true } },
    { event: 'SEND BID', properties: { time: 1725854487, distinct_id: 'sahno@icloud.com', $insert_id: 'CkAtDxsrkimBwdFtyuuiCwqgrkdtwwnCBtmk', $lib_version: '0.18.0', $mp_api_endpoint: 'api.mixpanel.com', $mp_api_timestamp_ms: 1725854487063, $user_id: 'sahno@icloud.com', coverLetter: 'Hey there!\n' + '\n' + "I'm Tamila Rozkova and I’d absolutely love to help you create a customizer for your Shopify website! 🎨🛍️ I think I'm a solid fit for this job because I've got a strong background in web development and have worked with Shopify before", employerAvgHourRatePaid: '70$/hour', employerHireRate: '50%', employerTotalRating: 4.9, employerTotalSpent: '$7K+', freelancer: 'Tamila Rozkova', mp_lib: 'node', mp_processing_time_ms: 1725854488078, name_event: 'SEND BID', publishedDate: 'Posted 43 minutes ago', questionAnswerPairs: null, requiredConnects: '19 Connects', scanName: '🇺🇸 Tamila Rozhkova', targetLink: 'https://www.upwork.com/jobs/~021832981615371268905', team: 'BandIT', test: true } },
    { event: 'REJECT BID', properties: { time: 1725861649, distinct_id: 'sahno@icloud.com', $insert_id: 'jAnEvyBrEbsAdqycwFrgAChdzonbCamunFzF', $lib_version: '0.18.0', $mp_api_endpoint: 'api.mixpanel.com', $mp_api_timestamp_ms: 1725861649586, $user_id: 'sahno@icloud.com', error: 'Rating 0', freelancer: 'Tamila Rozkova', mp_lib: 'node', mp_processing_time_ms: 1725861650604, name_event: 'REJECT BID', scanName: '🇺🇸 Tamila Rozhkova', team: 'BandIT', test: true } },
    { event: 'SEND BID', properties: { time: 1725861687, distinct_id: 'sahno@icloud.com', $insert_id: 'utxxwhdEviFfDedcuDumminldlltwhACywvx', $lib_version: '0.18.0', $mp_api_endpoint: 'api.mixpanel.com', $mp_api_timestamp_ms: 1725861687856, $user_id: 'sahno@icloud.com', coverLetter: 'Hey there! 😊\n' + '\n' + "I'm Tamila Rozkova and I'm excited about your Wordpress Site project. I'm really passionate about creating websites that are not only visually engaging but also highly functional. 🎨✨\n" + '\n' + '1/ On average, it usually takes me around 30-40 h', employerAvgHourRatePaid: '15.24$/hour', employerHireRate: '89%', employerTotalRating: 4.9, employerTotalSpent: '$10K+', freelancer: 'Tamila Rozkova', mp_lib: 'node', mp_processing_time_ms: 1725861688789, name_event: 'SEND BID', publishedDate: 'Posted 47 minutes ago', questionAnswerPairs: null, requiredConnects: null, scanName: '🇺🇸 Tamila Rozhkova', targetLink: 'https://www.upwork.com/jobs/~021833010867503053596', team: 'BandIT', test: true } },
    { event: 'SEND BID', properties: { time: 1725872485, distinct_id: 'sahno@icloud.com', $insert_id: 'iuqvbaboeEwzoptpweiwnquwBxgcrxdBCiwy', $lib_version: '0.18.0', $mp_api_endpoint: 'api.mixpanel.com', $mp_api_timestamp_ms: 1725872485840, $user_id: 'sahno@icloud.com', coverLetter: 'Hi Team,\n' + '\n' + "Hope you're doin' well! 😊 I'm Tamila Rozkova, and I gotta say, I'm super excited about the opportunity to work on your WordPress landing pages. \n" + '\n' + "I think I'm a good fit for this job because I've got a bunch of experience in creating, optimizi", employerAvgHourRatePaid: '31.93$/hour', employerHireRate: '74%', employerTotalRating: 5, employerTotalSpent: '$20K+', freelancer: 'Tamila Rozkova', mp_lib: 'node', mp_processing_time_ms: 1725872488050, name_event: 'SEND BID', publishedDate: 'Posted 29 minutes ago', questionAnswerPairs: null, requiredConnects: '22 Connects', scanName: '🇺🇸 Tamila Rozhkova', targetLink: 'https://www.upwork.com/jobs/~021833060508958619979', team: 'BandIT', test: true } },
    { event: 'REJECT BID', properties: { time: 1725879653, distinct_id: 'sahno@icloud.com', $insert_id: 'jgciwiEzskAofxwwmDvjmawlqjxtzzsiqmmb', $lib_version: '0.18.0', $mp_api_endpoint: 'api.mixpanel.com', $mp_api_timestamp_ms: 1725879653603, $user_id: 'sahno@icloud.com', error: 'Rating 0', freelancer: 'Tamila Rozkova', mp_lib: 'node', mp_processing_time_ms: 1725879655616, name_event: 'REJECT BID', scanName: '🇺🇸 Tamila Rozhkova', team: 'BandIT', test: true } },
];

const Home = () => {
    return (
        <div>
            <h1>Home page</h1>
            <EventChart data={eventData} />
        </div>
    );
};

export default Home;
